# Generated by Django 6.0.1 on 2026-02-21 13:05

import apps.core.models.model_ml
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome a ser exibido para o usuário', max_length=100, verbose_name='Nome do modelo')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='descrição')),
                ('tipo', models.IntegerField(choices=[(0, 'Classificação'), (1, 'Regressão')], help_text='Explicita se é um modelo de classificação ou regressão', verbose_name='Tipo do modelo')),
                ('is_public', models.BooleanField(db_default=True, default=True, help_text='Define se pode ser acessado por um usuário anônimo', verbose_name='é publico?')),
                ('arquivo', models.FileField(upload_to=apps.core.models.model_ml.owner_folder)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Ultima atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('owner', models.ForeignKey(help_text='Dono do modelo', on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de Machine Learn',
                'verbose_name_plural': 'Modelos de Machine Learn',
            },
        ),
    ]
